<?xml version="1.0" ?>

<!DOCTYPE carstore [
<!ELEMENT carstore (dealership)>
<!ELEMENT dealership (name, manager, contacts, website, annotation-dealer, category)>
<!ATTLIST dealership location CDATA #FIXED "Veliko Tarnovo">
<!ELEMENT name (#PCDATA)>
<!ENTITY name "Индиго">
<!ELEMENT manager (#PCDATA)>
<!ENTITY manager "Мартин">
<!ELEMENT contacts (email, address)>
<!ATTLIST contacts phone CDATA #REQUIRED>
<!ELEMENT email (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ENTITY address "ул. Улична 17">
<!ELEMENT website (html:a)>
<!ENTITY website "Indigo.com">
<!ATTLIST website xmlns:html CDATA "http://www.w3.org/1999/xhtml">
<!ELEMENT html:a (#PCDATA)>
<!ATTLIST html:a href CDATA "https://blueonn33.github.io/martinmarinov/">
<!ELEMENT annotation-dealer (#PCDATA)>
<!ELEMENT category (car, truck, moto)>
<!ELEMENT car (car-id+)>
<!ELEMENT car-id (brand, model, year, price, color, km, power, fuel-type, transmission, condition, annotation, image, link)>
<!ELEMENT brand (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT km (#PCDATA)>
<!ELEMENT power (#PCDATA)>
<!ATTLIST power unit CDATA #REQUIRED>
<!ATTLIST price currency CDATA #REQUIRED>
<!ELEMENT fuel-type (#PCDATA)>
<!ELEMENT transmission (#PCDATA)>
<!ELEMENT condition (#PCDATA)>
<!ELEMENT annotation (#PCDATA)>
<!ATTLIST annotation lang CDATA "BG">
<!ELEMENT image (html:img+)>
<!ATTLIST image xmlns:html CDATA "http://www.w3.org/1999/xhtml">
<!ELEMENT html:img (#PCDATA)>
<!ATTLIST html:img src CDATA "">
<!ELEMENT link (html:a+)>
<!ATTLIST link xmlns:html CDATA "http://www.w3.org/1999/xhtml">
<!ATTLIST car-id type NMTOKENS "SUV Luxury Sport" rating CDATA "0">

<!ELEMENT truck (truck-id+)>
<!ELEMENT truck-id (brand, model, year, price, color, km, power, fuel-type, transmission, condition, annotation, image, link)>
<!ATTLIST truck-id type NMTOKENS "SUV Luxury Sport" rating CDATA "0">

<!ELEMENT moto (moto-id+)>
<!ELEMENT moto-id (brand, model, year, price, color, km, power, fuel-type, transmission, condition, annotation, image, link)>
<!ATTLIST moto-id type NMTOKENS "SUV Luxury Sport" rating CDATA "0">
]>

<?xml-stylesheet type="text/css" href="styles/Carstore5.css"?>
<carstore>
    <dealership location="Veliko Tarnovo">
        <name>&name;</name>
        <manager>&manager;</manager>
        <contacts phone="095898549594">
            <email>m.marinov17@gmail.com</email>
            <address>&address;</address>
        </contacts>
        <website xmlns:html="http://www.w3.org/1999/xhtml">
            <html:a href="https://blueonn33.github.io/martinmarinov/">&website;</html:a>
        </website>
        <annotation-dealer>BG</annotation-dealer>
        
        <category>
            <car>
                <car-id type="SUV" rating="10">
                    <brand>Aston Martin</brand>
                    <model>Vulcan</model>
                    <year>2025</year>
                    <price currency="EUR">1200000</price>
                    <color>Лилав</color>
                    <km>1172</km>
                    <power unit="hp">790</power>
                    <fuel-type>бензин</fuel-type>
                    <transmission>Ръчна</transmission>
                    <condition>Използван</condition>
                    <annotation lang="BG">BG</annotation>
                    <image xmlns:html="http://www.w3.org/1999/xhtml">
                        <html:img src="images/aston-martin/vulcan-1.jpg" />
                        <html:img src="images/aston-martin/vulcan-2.jpg" />
                    </image>
                    <link xmlns:html="http://www.w3.org/1999/xhtml">
                        <html:a href="https://www.astonmartin.com/en">Aston Martin</html:a>
                    </link>
                </car-id>
                
                <car-id type="Sport" rating="9">
                    <brand>Aston Martin</brand>
                    <model>Vulcan</model>
                    <year>2025</year>
                    <price currency="EUR">400000</price>
                    <color>Черен</color>
                    <km>117</km>
                    <power unit="hp">550</power>
                    <fuel-type>бензин</fuel-type>
                    <transmission>Ръчна</transmission>
                    <condition>Нов</condition>
                    <annotation lang="BG">BG</annotation>
                    <image xmlns:html="http://www.w3.org/1999/xhtml">
                        <html:img src="images/aston-martin/vulcan-3.jpg" />
                        <html:img src="images/aston-martin/vulcan-2.jpg" />
                    </image>
                    <link xmlns:html="http://www.w3.org/1999/xhtml">
                        <html:a href="https://www.astonmartin.com/en">Aston Martin</html:a>
                    </link>
                </car-id>
                
                <car-id type="SUV" rating="8">
                    <brand>Maserati</brand>
                    <model>MC20</model>
                    <year>2024</year>
                    <price currency="EUR">190000</price>
                    <color>Бял</color>
                    <km>11347</km>
                    <power unit="hp">750</power>
                    <fuel-type>бензин</fuel-type>
                    <transmission>Ръчна</transmission>
                    <condition>Използван</condition>
                    <annotation lang="BG">BG</annotation>
                    <image xmlns:html="http://www.w3.org/1999/xhtml">
                        <html:img src="images/maserati/mc20-1.jpg" />
                    </image>
                    <link xmlns:html="http://www.w3.org/1999/xhtml">
                        <html:a href="https://www.maserati.com/bg/bg/dealers/autoitalia">Maserati</html:a>
                    </link>
                </car-id>
            </car>
            
            <truck>
                <truck-id type="Luxury">
                    <brand>Mercedes</brand>
                    <model>eActros 600</model>
                    <year>2024</year>
                    <price currency="EUR">300000</price>
                    <color>Сив</color>
                    <km>110383</km>
                    <power unit="hp">450</power>
                    <fuel-type>бензин</fuel-type>
                    <transmission>Ръчна</transmission>
                    <condition>Използван</condition>
                    <annotation lang="BG">BG</annotation>
                    <image xmlns:html="http://www.w3.org/1999/xhtml">
                        <html:img src="images/mercedes/e-1.webp" />
                    </image>
                    <link xmlns:html="http://www.w3.org/1999/xhtml">
                        <html:a href="https://www.mercedes-benz.bg/">Mercedes</html:a>
                    </link>
                </truck-id>
                
                <truck-id type="Electric">
                    <brand>Renault</brand>
                    <model>E-Tech T</model>
                    <year>2025</year>
                    <price currency="EUR">40000</price>
                    <color>Сив</color>
                    <km>17</km>
                    <power unit="hp">550</power>
                    <fuel-type>бензин</fuel-type>
                    <transmission>Ръчна</transmission>
                    <condition>Нов</condition>
                    <annotation lang="BG">BG</annotation>
                    <image xmlns:html="http://www.w3.org/1999/xhtml">
                        <html:img src="images/renault/t-1.jpg" />
                    </image>
                    <link xmlns:html="http://www.w3.org/1999/xhtml">
                        <html:a href="https://www.renault.bg/">Renault</html:a>
                    </link>
                </truck-id>
            </truck>
            
            <moto>
                <moto-id type="Sport">
                    <brand>Kawazaki</brand>
                    <model>Ninja</model>
                    <year>2025</year>
                    <price currency="EUR">75000</price>
                    <color>Зелен</color>
                    <km>20</km>
                    <power unit="hp">850</power>
                    <fuel-type>бензин</fuel-type>
                    <transmission>Ръчна</transmission>
                    <condition>Нов</condition>
                    <annotation lang="BG">BG</annotation>
                    <image xmlns:html="http://www.w3.org/1999/xhtml">
                        <html:img src="images/kawazaki/ninja-1.jpg" />
                    </image>
                    <link xmlns:html="http://www.w3.org/1999/xhtml">
                        <html:a href="https://www.kawasaki.com/en-us/">Kawazaki</html:a>
                    </link>
                </moto-id>
                
                <moto-id type="Sport">
                    <brand>Ducati</brand>
                    <model>Streetfighter</model>
                    <year>2022</year>
                    <price currency="EUR">50000</price>
                    <color>Червен</color>
                    <km>34000</km>
                    <power unit="hp">700</power>
                    <fuel-type>бензин</fuel-type>
                    <transmission>Ръчна</transmission>
                    <condition>Използван</condition>
                    <annotation lang="BG">BG</annotation>
                    <image xmlns:html="http://www.w3.org/1999/xhtml">
                        <html:img src="images/ducati/ducati-1.jpg" />
                    </image>
                    <link xmlns:html="http://www.w3.org/1999/xhtml">
                        <html:a href="https://ducati.bg/">Ducati</html:a>
                    </link>
                </moto-id>
            </moto>
        </category>
    </dealership>
</carstore>